# V-J Haanpää, 2024

title: "V-J's 'Angry Old Man Yells At Clouds' Blog" 
author: "Veli-Jussi Haanpää"
description: >- # this means to ignore newlines until "baseurl:"
  "<DESRIPTION> Write an awesome description for your new site here."

#domain: "vjhaanpaa.github.io"
#baseurl: "/vjhaanpaa.github.io/" # the subpath of your site, e.g. /blog
#url: "https://vjhaanpaa.github.io" # the base hostname & protocol for your site, e.g. http://example.com

email: "your-email@example.com"
#twitter_username: "vjhaanpaa"
github_username: "vjhaanpaa"
linkedin_username: "vjhaanpaa"
#facebook_username: username
#flickr_username: username
instagram_username: "vjhaanpaa"
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

# Build settings
theme: "minima"

minima:
  skin: solarized

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
